server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com #eureka服务端实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己这端就是注册中心,我的职责就是维护服务实例,并不需要去检索服务
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/ #设置与eureka server交互的地址,查询服务和注册服务都需要这个地址

