server:
  port: 8001


spring:
  application:
    name: cloud-hystrix-payment-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka/ #单机版,只注册到7001
  #      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka #集群版,注册到所有eureka服务注册中心
  instance:
    instance-id: payment8001
    prefer-ip-address: true